#!/bin/bash

CMDNAME=`basename $0`

function usage() {
  echo "----------" 1>&2
  echo -e "\033[0;31mUsage\033[0;39m: git chmail {OLD_MAIL_ADDRESS} {NEW_MAIL_ADDRESS}" 1>&2
  echo -e "\033[0;32mExamlpe\033[0;39m: git chmail \"foo@example.com\" \"bar@example.com\"" 1>&2
  echo "----------" 1>&2
  exit 1
}

if [ ${#} -eq 0 ]; then
  usage
  exit 1
fi


git filter-branch -f --commit-filter '
  if [ "$GIT_AUTHOR_EMAIL" = '${1}' ]; then
    GIT_AUTHOR_EMAIL='${2}';
    git commit-tree "$@";
  else
    git commit-tree "$@";
  fi' HEAD
